module.exports = {
  content: [
    {
      table: {
        widths: ["auto", "auto", "auto"],
        border: [false, false, false, false],
        style: "layoutTable",
        body: [
          [
            {
              text: "Gaspasa Mazatlan Sinaloa",
              border: [false, false, false, false],
            },
            { text: "T", border: [false, false, false, false] },
            {},
          ],
          [
            {
              colSpan: 3,
              border: [false, false, false, false],
              table: {
                style: "table",
                widths: [
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                  "auto",
                ],
                headerRows: 2,
                body: [
                  [
                    {
                      text: "Comisión por venta",
                      colSpan: 5,
                      alignment: "center",
                      style: "tableHeader",
                      bold: true,
                    },
                    {},
                    {},
                    {},
                    {},
                    {
                      text: "% Bono",
                      colSpan: 2,
                      alignment: "center",
                      style: "tableHeader",
                      bold: true,
                    },
                    {},
                    {
                      text: "Otras percepciones",
                      colSpan: 3,
                      alignment: "center",
                      style: "tableHeader",
                      bold: true,
                    },
                    {},
                    {},
                    {
                      text: "Otras percepciones",
                      colSpan: 5,
                      alignment: "center",
                      style: "tableHeader",
                      bold: true,
                    },
                    {},
                    {},
                    {},
                    {},
                  ],
                  [
                    {
                      text: "Header 1",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 2",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 3",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 4",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 5",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 6",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 7",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 8",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 9",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 10",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 11",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 12",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 13",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 14",
                      style: "tableHeader",
                      alignment: "center",
                    },
                    {
                      text: "Header 15",
                      style: "tableHeader",
                      alignment: "center",
                    },
                  ],
                ],
              },
            },
            {},
            {},
          ],
        ],
      },
    },
    {
      table: {
        style: "table",
        widths: [
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
          "auto",
        ],
        headerRows: 2,
        body: [
          [
            {
              text: "Comisión por venta",
              colSpan: 5,
              alignment: "center",
              style: "tableHeader",
              bold: true,
            },
            {},
            {},
            {},
            {},
            {
              text: "% Bono",
              colSpan: 2,
              alignment: "center",
              style: "tableHeader",
              bold: true,
            },
            {},
            {
              text: "Otras percepciones",
              colSpan: 3,
              alignment: "center",
              style: "tableHeader",
              bold: true,
            },
            {},
            {},
            {
              text: "Otras percepciones",
              colSpan: 5,
              alignment: "center",
              style: "tableHeader",
              bold: true,
            },
            {},
            {},
            {},
            {},
          ],
          [
            { text: "Header 1", style: "tableHeader", alignment: "center" },
            { text: "Header 2", style: "tableHeader", alignment: "center" },
            { text: "Header 3", style: "tableHeader", alignment: "center" },
            { text: "Header 4", style: "tableHeader", alignment: "center" },
            { text: "Header 5", style: "tableHeader", alignment: "center" },
            { text: "Header 6", style: "tableHeader", alignment: "center" },
            { text: "Header 7", style: "tableHeader", alignment: "center" },
            { text: "Header 8", style: "tableHeader", alignment: "center" },
            { text: "Header 9", style: "tableHeader", alignment: "center" },
            { text: "Header 10", style: "tableHeader", alignment: "center" },
            { text: "Header 11", style: "tableHeader", alignment: "center" },
            { text: "Header 12", style: "tableHeader", alignment: "center" },
            { text: "Header 13", style: "tableHeader", alignment: "center" },
            { text: "Header 14", style: "tableHeader", alignment: "center" },
            { text: "Header 15", style: "tableHeader", alignment: "center" },
          ],
        ],
      },
    },

    { text: "Column/row spans", pageBreak: "before", style: "subheader" },
    "Each cell-element can set a rowSpan or colSpan",
    {
      style: "tableExample",
      color: "#444",
      table: {
        widths: [200, "auto", "auto"],
        headerRows: 2,
        // keepWithHeaderRows: 1,
        body: [
          [
            {
              text: "Header with Colspan = 2",
              style: "tableHeader",
              colSpan: 2,
              alignment: "center",
            },
            {},
            { text: "Header 3", style: "tableHeader", alignment: "center" },
          ],
          [
            { text: "Header 1", style: "tableHeader", alignment: "center" },
            { text: "Header 2", style: "tableHeader", alignment: "center" },
            { text: "Header 3", style: "tableHeader", alignment: "center" },
          ],
          ["Sample value 1", "Sample value 2", "Sample value 3"],
          [
            {
              rowSpan: 3,
              text: "rowSpan set to 3\nLorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor",
            },
            "Sample value 2",
            "Sample value 3",
          ],
          ["", "Sample value 2", "Sample value 3"],
          ["Sample value 1", "Sample value 2", "Sample value 3"],
          [
            "Sample value 1",
            {
              colSpan: 2,
              rowSpan: 2,
              text: "Both:\nrowSpan and colSpan\ncan be defined at the same time",
            },
            "",
          ],
          ["Sample value 1", "", ""],
        ],
      },
    },
  ],
};
